/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * netMapIFrame.java
 *
 * Created on 15.05.2011, 20:32:04
 */
package com.googlecode.snoopycp.ui;

/**
 *
 * @author spiff
 */
import edu.uci.ics.jung.visualization.VisualizationViewer;
import java.awt.GridLayout;

public class netMapIFrame extends javax.swing.JInternalFrame {

    /** Creates new form netMapIFrame */
    public netMapIFrame() {
        initComponents();
        this.setClosable(true);
        this.setResizable(true);
        this.setMaximizable(true);
        this.graphPanel.setLayout(new GridLayout(1, 1));
    }
    
    public void add(VisualizationViewer<String, String> _add){
        this.graphPanel.add(_add);
    }
    
    public void updatePanel() {
        this.graphPanel.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscp = new javax.swing.JScrollPane();
        graphPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jscp.setViewportView(graphPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscp, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscp, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphPanel;
    private javax.swing.JScrollPane jscp;
    // End of variables declaration//GEN-END:variables
}
